@startuml routes__api__sessionLogin__server_ts
title routes/api/sessionLogin/+server.ts
class "routes/api/sessionLogin/+server.ts" as routes_api_sessionLogin__server_ts <<SvelteKitEndpoint>> {
  + async const POST
  + async const GET
}
note bottom of routes_api_sessionLogin__server_ts
  Imports:
    External:
    - $lib/firebase/firebase.admin
    - @sveltejs/kit
end note
@enduml
