@startuml routes__admin__survey__page_server_ts
title routes/admin/survey/+page.server.ts
class "routes/admin/survey/+page.server.ts" as routes_admin_survey__page_server_ts <<SvelteKitModule>> {
  + async const load
  + const actions
}
note bottom of routes_admin_survey__page_server_ts
  Imports:
    Local:
    - routes/admin/survey/$types
    External:
    - $lib/firebase/firebase.admin
    - @sveltejs/kit
end note
@enduml
