# Markdownlint configuration
# Disabled rules for cosmetic/style issues

# MD013: Line length - not enforced for documentation
MD013: false

# MD040: Code block language - not critical for documentation
MD040: false

# MD060: Table column style - cosmetic only
MD060: false
