@startuml server__routes__auth_ts
title server/routes/auth.ts
class "server/routes/auth.ts" as server_routes_auth_ts <<Module>> {
  + default default
}
note bottom of server_routes_auth_ts
  Imports:
    Local:
    - server/types/auth
    External:
    - $lib/firebase/firebase.admin
    - hono
    - hono/cookie
end note
@enduml
