@startuml server__routes__eventTypes_ts
title server/routes/eventTypes.ts
class "server/routes/eventTypes.ts" as server_routes_eventTypes_ts <<Module>> {
  + default default
}
note bottom of server_routes_eventTypes_ts
  Imports:
    Local:
    - server/middleware/auth
    - server/types/eventTypes
    - server/types/updateData
    External:
    - $lib/firebase/firebase.admin
    - hono
end note
@enduml
