@startuml server__routes__formTemplates_ts
title server/routes/formTemplates.ts
class "server/routes/formTemplates.ts" as server_routes_formTemplates_ts <<Module>> {
  + default default
}
note bottom of server_routes_formTemplates_ts
  Imports:
    Local:
    - server/middleware/auth
    - server/types/formTemplates
    - server/types/updateData
    External:
    - $lib/firebase/firebase.admin
    - hono
end note
@enduml
