@startuml server__routes__forms_ts
title server/routes/forms.ts
class "server/routes/forms.ts" as server_routes_forms_ts <<Module>> {
  + default default
}
note bottom of server_routes_forms_ts
  Imports:
    Local:
    - server/middleware/auth
    - server/types/forms
    External:
    - $lib/firebase/firebase.admin
    - hono
    - hono/cookie
end note
@enduml
