@startuml server__routes__guests_ts
title server/routes/guests.ts
class "server/routes/guests.ts" as server_routes_guests_ts <<Module>> {
  + default default
}
note bottom of server_routes_guests_ts
  Imports:
    Local:
    - server/types/guests
    External:
    - $lib/firebase/firebase.admin
    - hono
end note
@enduml
