@startuml server__routes__surveys_ts
title server/routes/surveys.ts
class "server/routes/surveys.ts" as server_routes_surveys_ts <<Module>> {
  + default default
}
note bottom of server_routes_surveys_ts
  Imports:
    Local:
    - server/middleware/auth
    - server/types/surveyData
    - server/types/surveys
    External:
    - $lib/firebase/firebase
    - $lib/firebase/firebase.admin
    - $lib/utils/firebaseCalls
    - hono
end note
@enduml
