@startuml server__routes__users_ts
title server/routes/users.ts
class "server/routes/users.ts" as server_routes_users_ts <<Module>> {
  + default default
}
note bottom of server_routes_users_ts
  Imports:
    Local:
    - server/middleware/auth
    - server/types/updateData
    - server/types/users
    External:
    - $lib/firebase/firebase
    - $lib/firebase/firebase.admin
    - hono
end note
@enduml
