@startuml routes__page_svelte
title routes/+page.svelte
class "routes/+page.svelte" as routes__page_svelte <<SvelteComponent>> {
  -- no exports --
}
note bottom of routes__page_svelte
  Imports:
    External:
    - svelte
end note
@enduml
