@startuml routes__api__users__server_ts
title routes/api/users/+server.ts
class "routes/api/users/+server.ts" as routes_api_users__server_ts <<SvelteKitEndpoint>> {
  + async const GET
}
note bottom of routes_api_users__server_ts
  Imports:
    External:
    - $lib/firebase/firebase.js
end note
@enduml
