@startuml lib__firebase__firebase_app_ts
title lib/firebase/firebase.app.ts
class "lib/firebase/firebase.app.ts" as lib_firebase_firebase_app_ts <<Module>> {
  + const db
  + const auth
}
note bottom of lib_firebase_firebase_app_ts
  Imports:
    External:
    - firebase/app
    - firebase/auth
    - firebase/firestore
end note
@enduml
