@startuml lib__firebase__firebase_ts
title lib/firebase/firebase.ts
class "lib/firebase/firebase.ts" as lib_firebase_firebase_ts <<Module>> {
  + const db
  + const auth
  + const bucket
}
note bottom of lib_firebase_firebase_ts
  Imports:
    Local:
    - ../serviceAccount.json
    External:
    - firebase-admin
    - firebase/auth
end note
@enduml
