@startuml lib__qr_code_ts
title lib/qr-code.ts
class "lib/qr-code.ts" as lib_qr_code_ts <<Module>> {
  + async const uploadFile
  + async const generateQRCode
  + async const deleteQRCode
}
note bottom of lib_qr_code_ts
  Imports:
    Local:
    - lib/firebase/firebase
    External:
    - qrcode
end note
@enduml
