@startuml routes__authentication__page_server_ts
title routes/authentication/+page.server.ts
class "routes/authentication/+page.server.ts" as routes_authentication__page_server_ts <<SvelteKitModule>> {
  + async const load
  + const actions
}
note bottom of routes_authentication__page_server_ts
  Imports:
    Local:
    - routes/authentication/$types
    External:
    - $lib/db/auth
    - @sveltejs/kit
    - firebase/firestore
end note
@enduml
