@startuml routes__admin__survey__id___NewQuestionForm_svelte
title routes/admin/survey/[id]/NewQuestionForm.svelte
class "routes/admin/survey/[id]/NewQuestionForm.svelte" as routes_admin_survey__id__NewQuestionForm_svelte <<SvelteComponent>> {
  + let questionEdit
}
note bottom of routes_admin_survey__id__NewQuestionForm_svelte
  Imports:
    External:
    - svelte
  
  Svelte props:
    - questionEdit
end note
@enduml
