@startuml lib__db__auth_ts
title lib/db/auth.ts
class "lib/db/auth.ts" as lib_db_auth_ts <<Module>> {
  + async function registerUser
  + async function signInUser
}
note bottom of lib_db_auth_ts
  Imports:
    External:
    - $lib/firebase/firebase.admin
end note
@enduml
