@startuml server__middleware__errorHandler_ts
title server/middleware/errorHandler.ts
class "server/middleware/errorHandler.ts" as server_middleware_errorHandler_ts <<Module>> {
  + async function errorHandler
}
note bottom of server_middleware_errorHandler_ts
  Imports:
    External:
    - hono
    - hono/http-exception
end note
@enduml
