@startuml routes__api__userResponses__server_ts
title routes/api/userResponses/+server.ts
class "routes/api/userResponses/+server.ts" as routes_api_userResponses__server_ts <<SvelteKitEndpoint>> {
  + async const GET
  + async const POST
  + async const PATCH
}
note bottom of routes_api_userResponses__server_ts
  Imports:
    External:
    - $lib/firebase/firebase.admin
    - $lib/utils/firebaseCalls
    - @sveltejs/kit
end note
@enduml
