@startuml routes__api__surveyQuestions__server_ts
title routes/api/surveyQuestions/+server.ts
class "routes/api/surveyQuestions/+server.ts" as routes_api_surveyQuestions__server_ts <<SvelteKitEndpoint>> {
  + async const GET
  + async const POST
  + async const DELETE
  + async const PATCH
}
note bottom of routes_api_surveyQuestions__server_ts
  Imports:
    External:
    - $lib/firebase/firebase.admin
end note
@enduml
