@startuml routes__admin__qrCode__page_svelte
title routes/admin/qrCode/+page.svelte
class "routes/admin/qrCode/+page.svelte" as routes_admin_qrCode__page_svelte <<SvelteComponent>> {
  + let data
  + let form
}
note bottom of routes_admin_qrCode__page_svelte
  Imports:
    Local:
    - routes/admin/qrCode/QRScanner.svelte
    External:
    - $app/forms
    - svelte/store
  
  Svelte props:
    - data
    - form
  
  Child components:
    - QrScanner
end note
@enduml
