@startuml routes__admin__qrCode__page_server_ts
title routes/admin/qrCode/+page.server.ts
class "routes/admin/qrCode/+page.server.ts" as routes_admin_qrCode__page_server_ts <<SvelteKitModule>> {
  + async function load
  + const actions
}
note bottom of routes_admin_qrCode__page_server_ts
  Imports:
    External:
    - $lib/firebase/firebase
    - $lib/qr-code.js
    - $lib/redisConfig
    - @sveltejs/kit
end note
@enduml
