@startuml routes__admin__qrCode__QRScanner_svelte
title routes/admin/qrCode/QRScanner.svelte
class "routes/admin/qrCode/QRScanner.svelte" as routes_admin_qrCode_QRScanner_svelte <<SvelteComponent>> {
  -- no exports --
}
note bottom of routes_admin_qrCode_QRScanner_svelte
  Imports:
    External:
    - html5-qrcode
end note
@enduml
