@startuml lib__utils__firebaseCalls_ts
title lib/utils/firebaseCalls.ts
class "lib/utils/firebaseCalls.ts" as lib_utils_firebaseCalls_ts <<Module>> {
  + async const fetchByQuery
  + async const fetchById
}
note bottom of lib_utils_firebaseCalls_ts
  Imports:
    External:
    - $lib/firebase/firebase.admin
end note
@enduml
