@startuml routes__api__logout__server_ts
title routes/api/logout/+server.ts
class "routes/api/logout/+server.ts" as routes_api_logout__server_ts <<SvelteKitEndpoint>> {
  + async const POST
}
note bottom of routes_api_logout__server_ts
  Imports:
    External:
    - @sveltejs/kit
end note
@enduml
