@startuml server__types__auth_ts
title server/types/auth.ts
class "server/types/auth.ts" as server_types_auth_ts <<Module>> {
  + interface UserRegistrationRequest
  + interface UserRegistrationResponse
  + interface UserSessionLoginRequest
  + interface UserSessionLoginResponse
  + interface UserWithClaims
  + interface UserLoginRequest
  + interface UserLoginResponse
}
@enduml
