@startuml server__types__forms_ts
title server/types/forms.ts
class "server/types/forms.ts" as server_types_forms_ts <<Module>> {
  + interface GuestUserDocument
  + interface UserDocument
  + interface ConsentFormSubmissionRequest
  + interface ConsentFormSubmissionResponse
  + interface DemographicsFormSubmissionRequest
  + interface DemographicsFormResponse
  + interface FormTemplateType
  + interface AgeCategory
}
@enduml
