@startuml server__types__users_ts
title server/types/users.ts
class "server/types/users.ts" as server_types_users_ts <<Module>> {
  + interface UserDocumentData
  + interface UserDocument
  + interface UserWithCustomClaims
  + interface EventCodeSubmissionRequest
  + interface EventCodeSubmissionResponse
  + interface UserProfileUpdateRequest
}
@enduml
